# Generated by Django 4.2.1 on 2023-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sports_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='text',
            new_name='sports',
        ),
        migrations.AddField(
            model_name='sport',
            name='subsports',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
