# Generated by Django 4.2.1 on 2023-05-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_rename_text_sport_sports_sport_subsports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Text',
            new_name='Categories',
        ),
    ]
