# Generated by Django 4.2.1 on 2023-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_detail_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_images'),
        ),
    ]
