# Generated by Django 4.2.1 on 2023-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detail_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='image',
        ),
        migrations.AddField(
            model_name='detail',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.image'),
        ),
    ]
