# Generated by Django 4.2.1 on 2023-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_image_remove_detail_image_detail_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='images',
        ),
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
