# Generated by Django 4.2.1 on 2023-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sport_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='detail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='detail_images'),
        ),
        migrations.AddField(
            model_name='detail',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='detail_images'),
        ),
    ]
